---

# elixir
# packages at https://github.com/elixir-lang/elixir/releases

- name: create package cache dir
  file: path=/home/{{rem_user}}/.pkg state=directory group={{rem_user}} owner={{rem_user}}

- name: get package
  become: no
  get_url:
    url:  https://github.com/elixir-lang/elixir/releases/download/v{{elixir_version}}/Precompiled.zip
    dest: /home/{{rem_user}}/.pkg/elixir-{{elixir_version}}.zip
    force: no

- name: create target directory
  become: no
  file: 
    path:  /home/{{rem_user}}/.pkg/elixir-{{elixir_version}}
    state: directory

- name: unzip package
  become: no
  unarchive:
    src:  /home/{{rem_user}}/.pkg/elixir-{{elixir_version}}.zip
    dest: /home/{{rem_user}}/.pkg/elixir-{{elixir_version}}
    remote_src: true

- name: installation symlinks
  become: yes
  file: 
    src:   /home/{{rem_user}}/.pkg/elixir-{{elixir_version}}/bin/{{item}} 
    dest:  /usr/local/bin/{{item}} 
    state: link
    force: yes
  with_items:
    - elixir
    - elixirc
    - iex
    - mix
        
# support for `:observer.start()`

# - name: add i386 architecture
#   become: yes
#   lineinfile:
#     dest: /var/lib/dpkg/arch
#     line: "i386"
#     create: yes

# - name: install support packages
#   become: yes
#   apt:
#     name: "{{item}}"
#     state: present
#   with_items:
#     - gtk2-engines
#     - gtk2-engines-*
#     - gtk2-engines-murrine:i386
#     - gtk2-engines-pixbuf:i386
#   when: is_x86_64 

# GET elixir SOURCE FOR DOCCO AND CODE LOOKUPS

- name: create package cache dir
  file: path=/home/{{rem_user}}/.beam_src state=directory group={{rem_user}} owner={{rem_user}}
  when: is_x86_64

- name: download Elixir tar file
  become: no
  get_url: 
    url:  https://github.com/elixir-lang/elixir/archive/v{{elixir_version}}.tar.gz
    dest: /home/{{rem_user}}/.beam_src/elixir-{{elixir_version}}.tar.gz
  when: is_x86_64

- name: expand Elixir tar file
  unarchive:
    src:  /home/{{rem_user}}/.beam_src/elixir-{{elixir_version}}.tar.gz
    dest: /home/{{rem_user}}/.beam_src
    remote_src: true
  when: is_x86_64

- name: create symlink to Elixir source dir
  file: 
    src:  /home/{{rem_user}}/.beam_src/elixir-{{elixir_version}}
    dest: /home/{{rem_user}}/.beam_src/elixir
    mode: "a+rx"
    state: link 
  when: is_x86_64

- name: tweak IEx configuration
  become: true
  copy:
    src:  "{{item}}"
    dest: /usr/local/bin/{{item}}
    mode: "a+rx"
  when: is_x86_64
  with_items:
    - iex
    - iex_original
