---

# server_base

- name: remove Ubuntu packages
  become: true
  apt:  pkg={{item}} state=absent
  with_items:
    - update-manager
    - gmusicbrowser
    - pidgin

# every day at 0030
- name: cron auto-update packages
  become: true
  cron: 
    name:   'apt_update' 
    minute: '30' 
    hour:   '0' 
    job:    'apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y'

