---

# server_base

- name: remove Ubuntu packages
  become: true
  apt:  pkg={{item}} state=absent
  with_items:
    - update-manager
    - gmusicbrowser
    - pidgin

# every day at 0100
- name: cron auto-update packages
  become: true
  cron: 
    name: 'apt_update' 
    hour: '1' 
    job:  'apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y'

# every day at 0300
- name: lan resync
  become: true
  cron: 
    name:   "lan resync"
    hour:   "3" 
    user:   "aleak"
    job:    "yg ; allgui 'yg;yi;yd' ; allgui 'yg;yi;yd' ; yg"

# every day at 0500
- name: offsite backup
  become: true
  cron: 
    name:   "offsite backup" 
    hour:   "5" 
    user:   "aleak"
    job:    "offsite_backup"

