---

# phantomjs

- name: install dependencies
  become: true
  apt:  pkg={{item}} install_recommends=no
  with_items:
    - fontconfig
    - libfontconfig

- name: install phantomjs
  copy: src=phantomjs211 dest=/usr/local/bin/phantomjs mode="a+rx"
  become: true
