---

# phoenix
# http://www.phoenixframework.org/docs/installation

- name: install inotify
  apt: pkg=inotify-tools state=latest install_recommends=yes

- name: create package cache dir
  file: path=/home/{{rem_user}}/.pkg state=directory group={{rem_user}} owner={{rem_user}}

- name: get package
  become: no
  get_url:
    #url:  https://github.com/phoenixframework/phoenix/releases/download/v{{phoenix_version}}/phoenix_new-{{phoenix_version}}.ez
    url:  https://github.com/phoenixframework/archives/raw/master/phoenix_new-{{phoenix_version}}.ez
    dest: /home/{{rem_user}}/.pkg/phoenix_new-{{phoenix_version}}.ez
    force: no

- name: install package
  become: no
  shell: echo Y | mix archive.install /home/{{rem_user}}/.pkg/phoenix_new-{{phoenix_version}}.ez
  args:
    creates: /home/{{rem_user}}/.mix/archives/phoenix_new-{{phoenix_version}}.ez
  
