---

# erlang

# FOR x86_64 (64 bit UBUNTU Dev Boxes and Servers)
# see http://www.erlang-solutions.com/downloads/download-erlang-otp
- name: ubuntu apt_key
  apt_key: 
    url: http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
  when: is_x86_64

- name: ubuntu repository
  apt_repository: 
    repo:  'deb http://packages.erlang-solutions.com/ubuntu trusty contrib' 
    state: present
  when: is_x86_64

- name: ubuntu remove non-compliant
  apt: pkg={{item}} state=absent
  with_items:
    - erlang
    - erlang-doc
    - erlang-manpages
  when: is_x86_64

- name: ubuntu package
  apt: pkg={{item}} state=latest 
  with_items:
    - esl-erlang
  when: is_x86_64

# FOR ARMV7L (32 bit RPi/Raspbian and Odroid-XU4)
# - compile script at 'files/armv7l/build.sh'
# - precompile erlang directory on an armv7l device
# - save the precompile in x-ansible/roles/erlang/files/armv7l/<release>
- name: copy release tarfile
  copy:
    src:  erl_{{erlang_armv7l_version}}.tar.gz
    dest: /home/{{rem_user}}/erl_{{erlang_armv7l_version}}.tar.gz
  when: is_armv7l

- name:  expand release tarfile
  shell: tar xf erl_{{erlang_armv7l_version}}.tar.gz
  args:
    chdir:   /home/{{rem_user}}
    creates: /home/{{rem_user}}/erl_{{erlang_armv7l_version}}
  when: is_armv7l

- name:  install armv7l erlang
  become:  yes
  shell: cp -R usr/* /usr
  args:
    chdir:   /home/{{rem_user}}/erl_{{erlang_armv7l_version}}
    creates: /usr/local/bin/erl
  when: is_armv7l

