---

# vscode editor

# - name: install package
#   apt: deb=/home/{{rem_user}}/var/data/vscode/code_{{vscode_version}}.deb

# - name: rsync .atom
#   become: no
#   connection: local
#   command: rsync -a --delete /home/{{lcl_user}}/.atom "{{ansible_hostname}}:" warn=false
#   when: lcl_hostname != ansible_hostname

- name: add apt key
  become: true
  apt_key: url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc state=present

- name: add an apt key 
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EB3E94ADBE1229CF

- name: add repository
  become: true
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib' state=present

- name: install package
  become: true
  apt: 
    pkg: virtualbox-5.1 
    state: latest
    update_cache: yes
