---

# vscode editor

- name: install package
  apt: deb=/home/{{rem_user}}/var/data/vscode/code_{{vscode_version}}.deb

# - name: rsync .atom
#   become: no
#   connection: local
#   command: rsync -a --delete /home/{{lcl_user}}/.atom "{{ansible_hostname}}:" warn=false
#   when: lcl_hostname != ansible_hostname
