---

# vscode editor
 
- name: create pkg dir
  file: 
    path: /home/{{rem_user}}/.pkg 
    state: directory 
    group: "{{rem_user}}"
    owner: "{{rem_user}}"

- name: copy package
  copy:
    src:  ~/var/data/vscode/code_{{vscode_version}}.deb
    dest: /home/{{rem_user}}/.pkg/code_{{vscode_version}}.deb

- name: install package
  apt: 
    deb: /home/{{rem_user}}/.pkg/code_{{vscode_version}}.deb

