---

# btsync - BitTorrent Sync

- name: create btsync group
  group: name=btsync state=present

- name: create user directory
  become: true
  file: 
    path:  /home/{{rem_user}}/b
    owner: "{{rem_user}}"
    group: "{{rem_user}}"
    state: directory
    mode:  0755

- name: create sync directory
  become: true
  file: 
    path:  /home/{{rem_user}}/.sync
    owner: root
    group: root
    state: directory

- name: install executable
  become: true
  copy:
    src:  btsync
    dest: /usr/sbin/btsync
    mode: "a+rx"

- name: create support directories
  become: true
  file:
    path:  "{{item}}"
    state: directory
  with_items:
    - /etc/btsync
    - /var/run/btsync
    - /var/log/btsync

- name: install config
  become: true
  template: 
    src:   btsync.conf
    dest:  /etc/btsync/btsync.conf
    owner: root 
    group: root
    force: yes
    mode: "a+r,a-x"
  notify: restart btsync

- name: install startup script
  become: true
  template: 
    src:   btsync
    dest:  /etc/init.d/btsync
    owner: root 
    group: root
    force: yes
    mode: "a+rx"
  notify: restart btsync

- name: setup service
  become: true
  command: update-rc.d btsync enable

