---

# pip

- name: remove apt modules
  apt: name="{{item}}" state=absent purge=true force=true
  with_items:
    - httpie
    - pip
    - mkdocs
  
- name: install setuptools
  become: true
  apt: name=python-setuptools state=latest

- name: install pip
  become: true
  easy_install: name=pip state=latest

- name: install pip modules
  become: true
  pip: name="{{item}}" state=latest
  with_items:
    - httpie             # command-line http client
    - influxdb           # python client for influxdb
    - mkdocs             # static html documentation
    - mkdocs-material    # CSS theme for mkdocs
    - magic-wormhole     # file transfer tool for seed data

