---

# tor_browser
#

- name: create pkg dir
  file: 
    path: /home/{{rem_user}}/.pkg 
    state: directory 
    group: "{{rem_user}}"
    owner: "{{rem_user}}"

- name: get tar file
  become: no
  copy:
    src:  tor-browser-linux64-{{tor_browser_version}}_en-US.tar.xz 
    dest: /home/{{rem_user}}/.pkg/tor-browser-linux64-{{tor_browser_version}}_en-US.tar.xz

- name: extract tar file
  unarchive:
    src: /home/{{rem_user}}/.pkg/tor-browser-linux64-{{tor_browser_version}}_en-US.tar.xz
    dest: /home/{{rem_user}}/.pkg/tor-{{tor_browser_version}}
    remove_src: yes

- name: create symlink
  file:
    src: /home/{{rem_user}}/.pkg/tor-browser-{{tor_browser_version}}
    dest: /home/aleak/.pkg/tor-base
    state: link 

