---

# crystal-lang

- name: add repository key
  apt_key: 
    id:        09617FD37CC06B54
    keyserver: keys.gnupg.net
    state:     present

- name: add repository
  apt_repository:
    repo: 'deb http://dist.crystal-lang.org/apt crystal main'
    update_cache: yes

- name: add crystal
  apt: pkg={{item}} state=latest force=yes
  with_items:
    - crystal

