---

# ruby_gems

- name: install base gems
  become: no
  gem: name="{{item}}"
  with_items:
    - bundler
    - pry
    - hirb
    - colored
    - net-ssh
    - net-sftp
    - net-ping
    - radix62
    - octokit
    - highline
    - tmuxinator
    - influxdb-cli
    - faraday
    - multipart-post

