---

# atom editor

- name: create pkg dir
  file: path=/home/{{rem_user}}/.pkg state=directory group={{rem_user}} owner={{rem_user}}

- name: get deb file
  become: no
  get_url: 
    url: https://atom.io/download/deb
    dest: /home/{{rem_user}}/.pkg/atom.deb

- name: install package
  apt: deb=/home/{{rem_user}}/.pkg/atom.deb

- name: rsync .atom
  become: no
  connection: local
  command: rsync -a --delete /home/{{lcl_user}}/.atom "{{ansible_hostname}}:" warn=false
  when: lcl_hostname != ansible_hostname
