---

# unison - large file sync

- name: remove apt packages
  become: true
  apt:
    name:  "{{item}}"
    state: absent
    purge: yes
  with_items:
    - unison
    - unison-gtk

- name: install executable
  become: true
  copy:
    src:  x86_64/{{item}}-{{unison_vsn}}
    dest: /usr/bin/{{item}}
    mode: "a+rx"
  with_items:
    - unison
    - unison-gtk

