---
# elixir_version: 1.1.0    superseded 29 Sep 2015
# elixir_version: 1.1.1    superseded 01 Jan 2016
# elixir_version: 1.2.0    superseded 07 May 2016
# elixir_version: 1.2.5    superseded 07 Jun 2016
# elixir_version: 1.2.6    superseded 21 Jun 2016
elixir_version: 1.3.0
