---

# btsync - BitTorrent Sync

- name: remove init script
  file: path=/etc/init.d/btsync state=absent

- name: create user directory
  become: true
  file: 
    path:  /home/{{rem_user}}/b
    owner: "{{rem_user}}"
    group: "{{rem_user}}"
    mode:  0755
    state: directory
    recurse: yes

- name: create sync directory
  file: 
    path:  /home/{{rem_user}}/b/.sync
    owner: "{{rem_user}}"
    group: "{{rem_user}}"
    state: directory
    recurse: yes

- name: install executable
  become: true
  copy:
    src:  btsync
    dest: /usr/sbin/btsync
    mode: "a+rx"
  notify: restart btsync

#- name: remove old pid directory
#  become: true
#  file: path=/var/run/btsync state=absent
#
#- name: set /run permissions
#  become: true
#  file:
#    path: "{{item}}"
#    mode: "a+rwx"
#    state: directory
#  with_items:
#    - /run
#
#- name: touch pid file
#  become: true
#  file:
#    path: /var/run/btsync.pid
#    owner: "{{rem_user}}"
#    group: "{{rem_user}}"
#    mode:  "a+rw"
#    state: touch
#
- name: create support directories
  become: true
  file:
    path:  "{{item}}"
    state: directory
    mode:  "a+rx"
  with_items:
    - /etc/btsync
    - /var/log/btsync

- name: create logfile
  become: true
  file:
    path:  /var/log/btsync/btsync.log
    owner: "{{rem_user}}"
    group: "{{rem_user}}"
    mode:  "a+rw"
    state: touch

- name: install config
  become: true
  template: 
    src:   btsync.conf
    dest:  /etc/btsync/btsync.conf
    owner: root 
    group: root
    force: yes
    mode: "a+r,a-x"
  notify: 
    - reload systemd
    - restart btsync

- name: install unit file
  become: true
  template: 
    src:   btsync.service
    dest:  /etc/systemd/system/btsync.service
    owner: root 
    group: root
    force: yes
    mode: "a+rx"
  notify: 
    - reload systemd
    - restart btsync
  when: ansible_distribution_version == "15.10"

- name: install init script
  become: true
  template: 
    src: btsync
    dest: /etc/init.d/btsync
    owner: root
    group: root
    force: yes
    mode:  "a+rx"
  notify:
    - restart btsync
  when: ansible_distribution_version == "12.04"

- name: setup service
  become: true
  command: update-rc.d btsync enable
  when: ansible_distribution_version == "12.04"
