---

# tmux

- name: add PPA
  become: true
  apt_repository: repo=ppa:pi-rho/dev 
  when: is_x86_64

- name: install TMUX
  become: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - tmux
    - tmux-next

- name: install tmux.conf
  become: false
  template:
    src:  tmux.conf
    dest: /home/{{rem_user}}/.tmux.conf

# wemux

- name: install wemux github repo
  become: true
  git:
    repo:   "https://github.com/zolrath/wemux.git"
    dest:   "/usr/local/share/wemux"
    depth:  1
    force:  true
    update: true

- name: create wemux symlink to executable
  become: true
  file: 
    src: /usr/local/share/wemux/wemux
    dest: /usr/local/bin/wemux
    mode: "a+rx"
    state: link 

- name: install wemux.conf
  become: true
  template:
    src:  wemux.conf
    dest: /usr/local/etc/wemux.conf

