---

# tmux - old style

- name: remove TMUX PPA
  become: true
  apt_repository: repo=ppa:pi-rho/dev state=absent
  when: is_x86_64

- name: remove TMUX
  become: true
  apt:  pkg={{item}} state=absent
  with_items:
    - tmux
    - tmux-next

# note: tmux.conf is in ~/g/base_util/cfg/_tmux.conf

- name: install TMUX for x86_64
  become: true


# tmate - see tmate.io

- name: add TMATE PPA
  become: true
  apt_repository: repo=ppa:tmate.io/archive 

- name: install TMATE
  become: true
  apt:  pkg={{item}} state=latest
  with_items:
    - tmate
