---

# vim8

- name: remove old vim
  apt:  pkg={{item}} state=absent
  with_items:
    - vim-nox
    - vim

- name: vim PPA cleanup 
  become: true
  apt_repository: repo={{item}} state=absent
  with_items:
    - ppa:jonathonf/vim
    - ppa:pi-rho/dev

# - name: vim PPA
#   become: true
#   apt_repository: repo=ppa:pi-rho/dev

- name: install 
  become: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - vim-gnome                  # the vim program
    - exuberant-ctags            # vim file navigation

