---

# vim8

- name: remove old vim
  apt:  pkg={{item}} state=absent
  with_items:
    - vim-gnome
    - vim

- name: vim PPA
  become: true
  apt_repository: repo=ppa:jonathonf/vim state=absent

- name: install 
  become: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - vim-nox                    # the vim program
    - exuberant-ctags            # vim file navigation

