---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  when: ansible_distribution_version == "15.10"

- name: restart btsync
  service: name=btsync state=restarted
  become: true
