---

# neovim

- name: remove old PPA
  become: true
  apt_repository: repo=ppa:rudenko/neovim state=absent

- name: add PPA
  become: true
  apt_repository: repo=ppa:neovim-ppa/unstable

- name: install 
  become: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - neovim

- name: create config directory
  file:
    path: /home/{{rem_user}}/.config
    state: directory

- name: create config symlinks
  file:
    src:  /home/{{rem_user}}/{{item.src}}
    dest: /home/{{rem_user}}/{{item.dest}}
    state: link 
  with_items:
    - { src: '.vim'  , dest: '.config/nvim' }
    - { src: '.vimrc', dest: '.config/nvim/init.vim' }

- name: install neovim gem
  become: no
  gem: name=neovim state=latest
