---

# neovim

- name: remove old PPA
  become: true
  apt_repository: repo={{item}} state=absent
  with_items:
    - ppa:rudenko/neovim
    - ppa:neovim-ppa/unstable

- name: add PPA
  become: true
  apt_repository: repo=ppa:neovim-ppa/stable

- name: install 
  become: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - neovim

- name: create config directory
  file:
    path: /home/{{rem_user}}/.config
    state: directory

- name: install neovim gem
  become: no
  gem: name=neovim state=latest

- name: install neovim package for python
  become: yes
  pip: name=neovim state=latest

- name: install neovim package for node
  become: yes
  npm: name=neovim state=latest global=yes

